# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohisee < Formula
  desc "TUI Item Tracker for Dark Souls Remastered Item Randomizers"
  homepage "https://github.com/cometpuppy/ohisee"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_darwin_amd64.tar.gz"
      sha256 "f870bc6fe346eb23ddd3550f43781fbf069d4fd3707b1da9fa00c369c32de873"

      define_method(:install) do
        bin.install "ohisee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_darwin_arm64.tar.gz"
      sha256 "1cc2e003f3637d69475af3848f14fa8d08216d896c6519df05cf8864200dde1b"

      define_method(:install) do
        bin.install "ohisee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_linux_amd64.tar.gz"
      sha256 "31a6a60123a54e85a274ee1962ef4c66c6a740779ea99fcb3fceb7b8f8754aaa"
      define_method(:install) do
        bin.install "ohisee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_linux_arm64.tar.gz"
      sha256 "e3422c8080674e2014cda2e84a40b8f0323b9e2b8d8422bfc1787e3aae930765"
      define_method(:install) do
        bin.install "ohisee"
      end
    end
  end
end
