# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohisee < Formula
  desc "TUI Item Tracker for Dark Souls Remastered Item Randomizers"
  homepage "https://github.com/cometpuppy/ohisee"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_darwin_amd64.tar.gz"
      sha256 "90bc3c561a98f9e1f1b608e616962efdfc7977369947693981482eb7d473c9ca"

      define_method(:install) do
        bin.install "ohisee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_darwin_arm64.tar.gz"
      sha256 "95ff500ea33917cefa63638ec37dd3e5c71544f236974fde0a38100499b7a73e"

      define_method(:install) do
        bin.install "ohisee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_linux_amd64.tar.gz"
      sha256 "ff16d80fcf71a098917599091c9c1258d301d69e73244f7c58d26ecf8bd8045b"
      define_method(:install) do
        bin.install "ohisee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cometpuppy/ohisee/releases/download/v0.9.0/ohisee_linux_arm64.tar.gz"
      sha256 "674b948c44562408804766627e7869a4824ec8733d8683a7c10cd8e977cec6b6"
      define_method(:install) do
        bin.install "ohisee"
      end
    end
  end
end
